Repository rat-pac/ratpac-two, pull requests merged in 2024-12, with the labels that each got.

#211 SetBranchValue now calls TTree->SetBranchAddress correctly
  src/io/include/RAT/OutNtupleProc.hh
Labels: Structure, merge soon

#210 Correctly count component-wise photon processes
  src/core/src/Gsim.cc
Labels: Optics, merge soon

#202 Add volume tracking to outntuples
  src/io/include/RAT/OutNtupleProc.hh
  src/io/src/OutNtupleProc.cc
Labels: Feature, Reviewed, merge soon

#201 Add r14688 timing calibration + arxiv references
  ratdb/PMTCHARGE.ratdb
  ratdb/PMTTRANSIT.ratdb
Labels: Photodetectors, merge soon

#203 Add Gaussian waveform analysis processor
  ratdb/DIGITIZER_ANALYSIS.ratdb
  ratdb/IO.ratdb
  src/cmd/src/ProcBlockManager.cc
  src/daq/CMakeLists.txt
  src/daq/include/RAT/WaveformAnalysisGaussian.hh
  src/daq/src/WaveformAnalysisGaussian.cc
Labels: Waveform Processing, Reviewed, merge soon

#212 Add rattests
  .github/workflows/rattests-workflow.yml
  .github/workflows/rattests.yml
  doc/users_guide/rattest.rst
  python/rattest.py
  python/rattest/__init__.py
  test/full/acrylic_attenuation/acrylic_attenuation.C
  test/full/acrylic_attenuation/standard.root
Labels: Feature, merge soon

#183 Write sensible PulseStartTime
  src/daq/include/RAT/PMTPulse.hh
  src/daq/src/PMTWaveform.cc
  src/daq/src/PMTWaveformGenerator.cc
Labels: Waveform Processing, merge soon

#213 Fixing docs link in README
  README.md
Labels: Documentation
