Repository rat-pac/ratpac-two, pull requests merged in 2025-01, with the labels that each got.

#219 Add tungsten alloy EA17 in MATERIALS.ratdb
  ratdb/MATERIALS.ratdb
Labels: Feature, merge soon

#218 Fix a bug in waveform util
  src/util/src/WaveformUtil.cc
Labels: Waveform Processing, merge soon

#206 added charge scale factor in channel status
  ratdb/CHANNEL_STATUS_DEFAULTS.ratdb
  src/core/include/RAT/Gsim.hh
  src/core/src/Gsim.cc
  src/ds/include/RAT/DS/ChannelStatus.hh
  src/io/include/RAT/OutNtupleProc.hh
  src/io/src/OutNtupleProc.cc
Labels: Photodetectors, merge soon

#215 have fitcentroid correctly set position to be invalid when charge = 0.
  src/fit/src/FitCentroidProc.cc
Labels: Reconstruction, merge soon

#200 Set global RAT-PAC2 compile flag to `-Wall -Werror`
  CMakeLists.txt
  src/core/include/RAT/Log.hh
  src/daq/include/RAT/WaveformAnalysis.hh
  src/daq/src/AfterPulseProc.cc
  src/daq/src/NoiseProc.cc
  src/daq/src/PMTPulse.cc
  src/daq/src/WaveformAnalysis.cc
  src/daq/src/WaveformAnalyzerBase.cc
  src/daq/src/WaveformPrep.cc
  src/ds/include/RAT/DS/Classifier.hh
  src/ds/src/MCPMT.cc
  src/fit/src/FitTensorProc.cc
  src/gen/src/GLG4PosGen.cc
  src/gen/src/Gen_LED.cc
  src/gen/src/HeGen.cc
  src/gen/src/LiGen.cc
  src/gen/src/NGen.cc
  src/gen/src/PosGen_RegexFill.cc
  src/gen/src/SNgen.cc
  src/gen/src/VertexGen_CRY.cc
  src/gen/src/VertexGen_FastNeutron.cc
  src/geo/src/BWVetGenericChamber.cc
  src/geo/src/GeoCalibrationStickFactory.cc
  src/geo/src/GeoCherenkovSourceFactory.cc
  src/geo/src/Materials.cc
  src/io/src/OutNtupleProc.cc
  src/physics/include/RAT/QuenchingCalculator.hh
  src/physics/src/GLG4Scint.cc
  src/physics/src/PhysicsList.cc
  src/ratbase/src/Rat.cc
  src/util/include/RAT/GLG4StringUtil.hh
  src/util/include/RAT/WaveformUtil.hh
  src/util/src/GLG4StringUtil.cc
  src/util/src/WaveformUtil.cc
  tools/ratdb2json/ratdb2json.cpp
Labels: Structure, merge soon

#222 Specify experiment binaries with rattests
  python/rattest.py
  python/rattest/__init__.py
Labels: merge soon

#217 Handle edge case when trigger width is less than trigger resolution.
  src/daq/src/SplitEVDAQProc.cc
Labels: DAQ, merge soon

#208 New waveform analysis class to interpolate waveforms using tapered sinc kernel
  ratdb/DIGITIZER_ANALYSIS.ratdb
  ratdb/IO.ratdb
  src/cmd/src/ProcBlockManager.cc
  src/daq/CMakeLists.txt
  src/daq/include/RAT/WaveformAnalysisSinc.hh
  src/daq/src/WaveformAnalysisSinc.cc
Labels: Waveform Processing, merge soon

#227 add better way to track mcpe pmt id
  src/io/include/RAT/OutNtupleProc.hh
  src/io/src/OutNtupleProc.cc
Labels: merge soon

#224 Add a forced trigger option that ignores the light in the detector
  ratdb/DAQ.ratdb
  src/cmd/src/ProcBlockManager.cc
  src/daq/CMakeLists.txt
  src/daq/include/RAT/ForcedTriggerProc.hh
  src/daq/include/RAT/SplitEVDAQProc.hh
  src/daq/src/ForcedTriggerProc.cc
  src/daq/src/SplitEVDAQProc.cc
Labels: merge soon

#226 Fitter interface
  ratdb/FITTER.ratdb
  src/ds/include/RAT/DS/WaveformAnalysisResult.hh
  src/fit/include/RAT/FitCentroidProc.hh
  src/fit/include/RAT/FitterInputHandler.hh
  src/fit/src/FitCentroidProc.cc
Labels: merge soon

#230 Add support for specifying run number and other extra rat flags.
  python/rattest/__init__.py
Labels: merge soon
