Repository rat-pac/ratpac-two, pull requests merged in 2025-05, with the labels that each got.

#260 Add more fields for data processing
  ratdb/IO.ratdb
  src/ds/include/RAT/DS/Calib.hh
  src/ds/include/RAT/DS/EV.hh
  src/io/include/RAT/OutNtupleProc.hh
  src/io/src/OutNtupleProc.cc
Labels: merge soon

#263 Allow channel status indexing to be different for every column
  ratdb/CHANNEL_STATUS_DEFAULTS.ratdb
  ratdb/RUN.ratdb
  src/ds/include/RAT/DS/ChannelStatus.hh
Labels: merge soon

#236 Add stopped pion neutrino source flux as option for generators to sample
  doc/users_guide/generators/vertex/es.rst
  macros/examples/es.mac
  ratdb/STPI.ratdb
  src/gen/src/CCgen.cc
  src/gen/src/ESgen.cc
Labels: merge soon

#270 Add a word for event cleaning
  src/ds/include/RAT/DS/EV.hh
  src/io/include/RAT/OutNtupleProc.hh
  src/io/src/OutNtupleProc.cc
Labels: merge soon

#272 Add procset functions to Quad fitter
  macros/examples/quadfitter.mac
  src/fit/include/RAT/FitQuadProc.hh
  src/fit/src/FitQuadProc.cc
Labels: merge soon

#205 Add RooTracker_Gen to source events from GENIE RooTracker
  doc/users_guide/generators/toplevel.rst
  doc/users_guide/generators/toplevel/rootracker.rst
  src/core/src/Gsim.cc
  src/gen/CMakeLists.txt
  src/gen/include/RAT/RooTracker_Gen.hh
  src/gen/src/RooTracker_Gen.cc
Labels: Generators

#269 Some documentation changes
  doc/README.md
  doc/programmers_guide/programmer_processors.rst
  doc/users_guide/command_interface.rst
  doc/users_guide/daq.rst
  doc/users_guide/database.rst
  doc/users_guide/digitization.rst
  doc/users_guide/index.rst
  doc/users_guide/outputs.rst
  doc/users_guide/pmt.rst
  doc/users_guide/processors.rst
  doc/users_guide/producers_processors.rst
  doc/users_guide/reconstruction.rst
  doc/users_guide/user_processors.rst
  doc/users_guide/waveform_analysis.rst
Labels: Ready to merge

#273 Enable markdown (the objectively superior markup language) for documentation
  doc/conf.py
  doc/requirements.txt
Labels: Documentation, merge soon

#282 Remove more stuff related to the old analyzer code
  ratdb/DAQ.ratdb
  src/ds/include/RAT/DS/DigitPMT.hh
Labels: DAQ, merge soon

#268 Macro organization
  macros/examples/electron.mac
  macros/examples/led.mac
  macros/examples/photon_bomb.mac
  macros/examples/walltime.mac
  macros/validation/generators/examine_led.py
  macros/vis_gen_demo/gen_Li8.mac
  macros/vis_gen_demo/gen_electron_gun_point.mac
  macros/vis_gen_demo/gen_gamma_point_Y_1_MeV.mac
  macros/vis_gen_demo/gen_muon_point_1_GeV.mac
  macros/vis_gen_demo/gen_pbomb.mac
  macros/vis_gen_demo/gen_promptPositron.mac
  macros/vis_gen_demo/readme
  macros/visualizations/vis_nestedTubeArrays.mac
  macros/visualizations/vis_sno.mac
  macros/visualizations/vis_superk.mac
  macros/visualizations/vis_validation_geo.mac
  macros/visualizations/vis_validation_geo_leds.mac
Labels: merge soon, macros

#280 Documentation updates continued..
  doc/programmers_guide/programmer_processors.rst
  doc/users_guide/daq.rst
  doc/users_guide/digitization.rst
  doc/users_guide/index.rst
  doc/users_guide/photon_processes.rst
  doc/users_guide/physics_processes.rst
  doc/users_guide/pmt.rst
  doc/users_guide/processors.rst
  doc/users_guide/waveform_analysis.rst
  src/core/src/Gsim.cc
Labels: Documentation, merge soon

#283 Documentation update for RATDB and install procedure.
  doc/users_guide/database.rst
  doc/users_guide/installation.rst
Labels: Documentation, merge soon

#286 Addition of nested tube hits option in IO.ratdb
  ratdb/IO.ratdb
Labels: Bug, merge soon

#279 Move most cleanup activity to the `EndOfRun` branch
  src/io/include/RAT/OutNtupleProc.hh
  src/io/src/OutNtupleProc.cc
Labels: Structure

#277 Fix Nhit in fitdirectioncenter
  macros/examples/fitdirectioncenter.mac
  src/fit/src/FitDirectionCenterProc.cc
Labels: Reconstruction, merge soon

#290 add brass 360 to MATERIALS.ratdb
  ratdb/MATERIALS.ratdb
Labels: Geometry
