Repository rat-pac/ratpac-two, pull requests merged in 2025-06, with the labels that each got.

#271 Handle fitter seeding in FitterInputHandler
  ratdb/FITTER.ratdb
  src/fit/include/RAT/FitterInputHandler.hh
Labels: Reconstruction, merge soon

#287 Reorganization of PMT documentation
  doc/users_guide/pmt.rst
  doc/users_guide/processors.rst
Labels: Documentation, merge soon

#274 Clean up a bunch of outdated processor code
  ratdb/DAQ.ratdb
  ratdb/DIGITIZER_ANALYSIS.ratdb
  src/cmd/src/ProcBlockManager.cc
  src/core/include/RAT/PruneProc.hh
  src/core/src/Gsim.cc
  src/core/src/PruneProc.cc
  src/daq/CMakeLists.txt
  src/daq/include/RAT/LessSimpleDAQ2Proc.hh
  src/daq/include/RAT/LessSimpleDAQProc.hh
  src/daq/include/RAT/MiniCleanPMTCharge.hh
  src/daq/include/RAT/TrueDAQProc.hh
  src/daq/include/RAT/WaveformAnalysisLognormal.hh
  src/daq/src/LessSimpleDAQ2Proc.cc
  src/daq/src/LessSimpleDAQProc.cc
  src/daq/src/MiniCleanPMTCharge.cc
  src/daq/src/TrueDAQProc.cc
  src/daq/src/WaveformAnalysisLognormal.cc
  src/util/CMakeLists.txt
  src/util/include/RAT/MultiChargeDist.hh
  src/util/src/MultiChargeDist.cc
Labels: DAQ

#292 Command Line Interface/Macro documentation
  doc/users_guide/command_interface.md
  doc/users_guide/command_interface.rst
Labels: Documentation

#298 Add ntuple documentation
  doc/users_guide/data_structure.rst
  doc/users_guide/outputs.rst
  doc/users_guide/waveform_analysis.rst
Labels: Documentation
