Repository rat-pac/ratpac-two, pull requests merged in 2025-03, with the labels that each got.

#234 Update DAQ processor documentation
  doc/users_guide/processors.rst
Labels: Documentation, merge soon

#232 Add cylindrical pmts
  src/geo/CMakeLists.txt
  src/geo/include/RAT/CylindricalPMTConstruction.hh
  src/geo/src/pmt/CylindricalPMTConstruction.cc
  src/geo/src/pmt/PMTConstruction.cc
Labels: merge soon

#221 Improve compatibility with dependencies.
  CMakeLists.txt
  src/CMakeLists.txt
  src/geo/CMakeLists.txt
  src/geo/include/RAT/GDMLParser.hh
  src/geo/include/RAT/GDMLWriteParamvol.hh
  src/geo/include/RAT/GDMLWriteSetup.hh
  src/geo/include/RAT/GDMLWriteSolids.hh
  src/geo/include/RAT/GDMLWriteStructure.hh
  src/geo/src/DetectorConstruction.cc
  src/geo/src/GDMLWriteStructure.cc
  src/geo/src/gdml/GDMLMessenger.cc
  src/geo/src/gdml/GDMLParser.cc
  src/geo/src/gdml/GDMLWriteParamvol.cc
  src/geo/src/gdml/GDMLWriteSetup.cc
  src/geo/src/gdml/GDMLWriteSolids.cc
  src/geo/src/gdml/GDMLWriteStructure.cc
Labels: merge soon

#247 Fix bug in threshold crossing interpolation
  src/util/src/WaveformUtil.cc
Labels: Waveform Processing

#241 Updated a check to prevent sinc processor from crashing
  src/daq/src/WaveformAnalysisSinc.cc
Labels: merge soon

#239 Changing quadfit result for failed fits.
  src/fit/src/FitQuadProc.cc
Labels: merge soon

#244 Add optical properties for borosilicate glasses
  ratdb/OPTICS.ratdb
Labels: merge soon
